project_id = "delvgmrcfaeubuixprwz"

[functions.sitemap]
verify_jwt = false

[functions.robots]
verify_jwt = false

[functions.google-search-console]
verify_jwt = false

[functions.ai-consultant]
verify_jwt = false

[functions.google-analytics]
verify_jwt = false

[functions.website-audit]
verify_jwt = false

[functions.competitor-analysis]
verify_jwt = false

[functions.keyword-research]
verify_jwt = false

[functions.generate-audit-pdf]
verify_jwt = false

[functions.generate-content]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.dataforseo]
verify_jwt = false

[functions.serpapi]
verify_jwt = false

[functions.auto-generate-content]
verify_jwt = false

[functions.generate-landing-page]
verify_jwt = false
