-- Phase 2: Seed SEO Landing Pages with existing static data
-- This populates the seo_landing_pages table so the Landing Pages admin tab works

INSERT INTO public.seo_landing_pages (
  slug, title, page_type, service_slug, industry_slug, location_slug,
  hero_headline, hero_subheadline, primary_cta, secondary_cta,
  problem_bullets, solution_bullets, key_metrics,
  testimonial_quote, testimonial_author, testimonial_role, testimonial_company,
  faq_list, process_steps, working_with_you, pricing_snapshot,
  target_keyword, meta_title, meta_description,
  related_case_studies, related_articles,
  is_published, is_featured
) VALUES
-- SEO for Trades & Home Services
(
  'seo-trades-home-services',
  'SEO for Trades & Home Services',
  'service-industry',
  'seo',
  'trades-home-services',
  NULL,
  'SEO for trades & home services that fills your diary, not just your rankings.',
  'We help plumbers, electricians, HVAC, roofers and home services win the local searches that turn into actual jobs – with pages and tracking set up to prove it.',
  'Get a trades SEO strategy call',
  'Request a local SEO & website audit',
  '["You''re buried under national directories and lead brokers in Google.","You rank for your brand name, but not for the jobs you actually want.","Your site gets visits, but most people bounce or never pick up the phone.","Google Business Profile is half-filled, outdated or full of random photos.","You''re paying for ads or SEO with no clear view of which calls came from where."]'::jsonb,
  '["Local SEO strategy focused on the jobs, locations and margins that matter.","Proper service-area pages and local landing pages that actually convert.","Google Business Profile optimisation and reviews strategy.","Tracking on calls, forms and quote requests so you can see which channels pay.","Simple dashboards you or your office manager can actually understand."]'::jsonb,
  '[{"value":"+74%","label":"Local Enquiries","description":"Increase in local enquiries in 6 months after rebuilding location pages"},{"value":"+36%","label":"Tracked Calls","description":"More calls tracked back to SEO after fixing Google Business profiles"},{"value":"-28%","label":"Lead Cost","description":"Lead cost down by shifting focus from lead brokers to owned channels"}]'::jsonb,
  'We''d been relying on word of mouth and some random ads. Once the local pages and profiles were sorted, the phones picked up – and we actually knew which jobs came from SEO vs everything else.',
  'Mark Thompson',
  'Owner',
  'Thompson Heating & Plumbing',
  '[{"question":"We''re a small team – is SEO overkill for us?","answer":"Not if you pick your battles. We focus on the services and areas that bring the best jobs, not trying to rank for every generic term in the country."},{"question":"We already get leads from Checkatrade/lead brokers. Why bother?","answer":"Those platforms will always take their cut. Building your own SEO assets means more direct enquiries, better margins and not being held hostage by a middleman."},{"question":"Can you handle multiple branches/areas?","answer":"Yes. We build a sensible structure for multiple locations so Google – and customers – know who to call where."},{"question":"How do we know it''s working?","answer":"We track calls, forms and quote requests by channel, so you can see exactly what SEO is doing for your pipeline."}]'::jsonb,
  NULL,
  NULL,
  NULL,
  'seo for trades',
  'SEO for Trades & Home Services | Avorria',
  'SEO for plumbers, electricians, HVAC and home services that fills your diary. Local SEO strategy, Google Business Profile optimization and conversion tracking.',
  '["multi-location-web-design","home-services-local-seo"]'::jsonb,
  '["local-seo-home-services","website-conversion-tips-trades"]'::jsonb,
  true,
  true
),
-- SEO for Professional Services
(
  'seo-professional-services',
  'SEO for Professional Services',
  'service-industry',
  'seo',
  'professional-services',
  NULL,
  'SEO for professional services that attracts better-fit clients, not more tyre-kickers.',
  'We design SEO around how serious buyers research firms like yours – and connect organic visibility to qualified enquiries, not random traffic.',
  'Book a professional services SEO call',
  'Request an SEO & website audit',
  '["You get plenty of contact form spam but few serious enquiries.","You rank for vague ''informational'' searches that never turn into work.","Your site reads like a brochure, not a trusted advisor.","There''s no clear path from content to enquiry, just a lonely ''contact us'' in the footer.","Partners want to see the commercial impact, not just rankings."]'::jsonb,
  '["Keyword strategy focused on high-intent, ''ready to talk'' search terms.","Service and sector pages that explain outcomes, not just credentials.","Thought-leadership and guides that feed real enquiries, not vanity metrics.","Clear, professional conversion paths (book a consultation, request a review, etc.).","Reporting that links organic visits to qualified leads and proposals."]'::jsonb,
  '[{"value":"+61%","label":"Qualified Enquiries","description":"Increase in qualified enquiries for a specialist B2B firm in 8 months"},{"value":"2x","label":"Organic Leads","description":"Doubling of organic leads from C-suite personas after restructuring content"},{"value":"Shorter","label":"Sales Cycles","description":"Shorter sales cycles when prospects arrive pre-educated via SEO content"}]'::jsonb,
  'SEO used to feel like a black box. We now know exactly which topics and pages are driving decent enquiries – and which to stop wasting time on.',
  'Claire Barton',
  'Partner',
  'Barton Legal Partners',
  '[{"question":"We have a long sales cycle – does SEO still help?","answer":"Yes. SEO is perfect for educating buyers early and mid-funnel, then capturing them when they''re ready to engage – provided it''s structured around your real buying journey."},{"question":"Are we going to have to write endless content?","answer":"Not unless it''s justified. We focus on high-impact pieces and can handle planning, briefs and production with your team''s input."},{"question":"How do we avoid attracting the wrong type of client?","answer":"Positioning and messaging. We shape topics, language and calls-to-action so your ideal client recognises themselves – and the wrong ones self-select out."},{"question":"Can you work around compliance and brand guidelines?","answer":"Yes. We''re used to operating inside regulated environments and structured sign-off processes."}]'::jsonb,
  NULL,
  NULL,
  NULL,
  'seo for professional services',
  'SEO for Professional Services | Avorria',
  'SEO for law firms, consultancies and professional services that attracts better-fit clients. High-intent keyword strategy and conversion-focused content.',
  '["professional-services-seo","legal-services-seo-revenue"]'::jsonb,
  '["professional-services-content","seo-roi-measurement"]'::jsonb,
  true,
  false
),
-- SEO for B2B SaaS
(
  'seo-b2b-saas',
  'SEO for B2B SaaS',
  'service-industry',
  'seo',
  'b2b-saas',
  NULL,
  'B2B SaaS SEO that feeds your pipeline, not just your blog.',
  'We build SEO strategies around your ICP, pain points and product, then tie them into demos, trials and opportunities – not just ''traffic growth''.',
  'Talk B2B SaaS SEO',
  'Request a SaaS SEO audit',
  '["You''re ranking for top-of-funnel queries that never turn into trials.","Your blog is a random collection of topics, not structured demand capture.","There''s no clear bridge from SEO content to product pages and onboarding.","Attribution between content, trials and closed-won is a mess.","You get lots of sign-ups, few real users."]'::jsonb,
  '["ICP-focused keyword & topic mapping (by persona, problem, and stage).","Product-led SEO pages that show the ''job to be done'', not just features.","Playbooks and use case hubs that link to demos and trials.","Clean tracking from SEO entry points through to sign-ups and opportunities.","CRO on key pages (pricing, demo, sign-up) to improve trial → SQL."]'::jsonb,
  '[{"value":"2.1x","label":"Pipeline","description":"Organic-sourced pipeline up in 12 months for a B2B SaaS platform"},{"value":"+89%","label":"Qualified Sign-ups","description":"Increase in product-qualified sign-ups from SEO after restructuring content"},{"value":"Better","label":"Lead Quality","description":"Fewer junk sign-ups, more demo requests from ICP accounts"}]'::jsonb,
  'We''d spent years writing content. Avorria restructured it around our ICP and product and suddenly SEO became a credible pipeline source, not just a brand activity.',
  'David Chen',
  'VP Marketing',
  'CloudFlow Solutions',
  '[{"question":"Do you do programmatic/at-scale pages?","answer":"Where it makes sense, yes – but only if it''s aligned to demand and avoids thin, spammy duplication."},{"question":"Can you plug into HubSpot/Salesforce for attribution?","answer":"Yes, we can work with your CRM to track SEO-originated sign-ups and opportunities properly."},{"question":"What about international SEO?","answer":"We can plan and implement multi-region, multi-language structures where the economics justify it."},{"question":"How quickly can we see impact?","answer":"Depending on your starting point, you''ll typically see early movement in 2–3 months and compounding gains beyond that."}]'::jsonb,
  NULL,
  NULL,
  NULL,
  'b2b saas seo',
  'B2B SaaS SEO | Pipeline-Focused SEO Services | Avorria',
  'B2B SaaS SEO that feeds your pipeline. ICP-focused keyword strategy, product-led content and clean attribution from SEO to demos and opportunities.',
  '["saas-paid-media","professional-services-seo"]'::jsonb,
  '["saas-content-strategy","attribution-professional-services"]'::jsonb,
  true,
  false
),
-- SEO for E-commerce Brands
(
  'seo-ecommerce-brands',
  'SEO for E-commerce Brands',
  'service-industry',
  'seo',
  'ecommerce-brands',
  NULL,
  'E-commerce SEO that moves revenue, not just rankings.',
  'We fix structure, categories and on-site SEO so that more of your organic traffic turns into actual orders – and we show you the uplift clearly.',
  'Book an e-commerce SEO call',
  'Get an e-commerce SEO audit',
  '["Category pages are thin, duplicated or impossible to navigate.","Product pages rely on manufacturer descriptions and look like everyone else''s.","You get decent organic sessions but weak add-to-cart and checkout rates.","Faceted navigation and filters are messing with crawl and indexation.","It''s hard to tell what SEO is actually worth in revenue."]'::jsonb,
  '["Category structure and internal linking designed for buyers and crawlers.","Upgraded product and category content that actually sells.","Tech clean-up around filters, duplicates, canonicalisation and indexation.","SEO + CRO on key templates to improve add-to-cart, checkout and AOV.","Clear reporting on organic revenue, not just traffic."]'::jsonb,
  '[{"value":"+47%","label":"Organic Revenue","description":"YoY after restructuring categories and templates"},{"value":"+32%","label":"Add-to-Cart Rate","description":"From organic sessions after CRO on key pages"},{"value":"Better","label":"Visibility","description":"Fewer orphaned products, more visibility on high-margin categories"}]'::jsonb,
  'We''d been chasing random keywords for years. Once the structure and templates were sorted, organic revenue finally started to look like the traffic graphs.',
  'Emma Caldwell',
  'E-commerce Director',
  'UrbanThread',
  '[{"question":"Which platforms do you work with?","answer":"Shopify, WooCommerce and most custom stacks. If your platform is genuinely holding you back, we''ll say so."},{"question":"Can you handle large catalogues?","answer":"Yes – but we prioritise ruthlessly. Not every product needs bespoke SEO; categories and key SKUs come first."},{"question":"Do you handle content and dev changes?","answer":"We can implement directly or provide dev-ready and content-ready briefs for your internal team."},{"question":"How do you measure success?","answer":"Organic revenue, assisted revenue, and improvements in key conversion steps – not just traffic volume."}]'::jsonb,
  NULL,
  NULL,
  NULL,
  'ecommerce seo',
  'E-commerce SEO Services | Revenue-Focused SEO | Avorria',
  'E-commerce SEO that moves revenue. Category structure, product optimization, technical clean-up and conversion-focused SEO strategy.',
  '["ecommerce-cro","multi-location-web-design"]'::jsonb,
  '["ecommerce-seo-guide","category-page-optimization"]'::jsonb,
  true,
  false
),
-- SEO for Multi-Location Brands
(
  'seo-multi-location-brands',
  'SEO for Multi-Location Brands',
  'service-industry',
  'seo',
  'multi-location-brands',
  NULL,
  'SEO for multi-location brands that keeps every site and profile pulling its weight.',
  'We bring order to the chaos of multiple locations, profiles and pages – so customers find the right place, in the right city, with the right information, every time.',
  'Discuss multi-location SEO',
  'Request a multi-location SEO audit',
  '["Each location has a slightly different, sometimes outdated web presence.","Some branches get all the leads; others barely see a contact form.","Google Business Profiles are inconsistent or unmanaged.","Location pages are cloned and thin, so Google doesn''t trust them.","Head office has no clear view of which locations win or lose in search."]'::jsonb,
  '["Global/local SEO strategy that respects brand but adapts to local realities.","Structured, unique location pages with local proof and CTAs.","GBProfile optimisation and process for reviews, photos and updates.","Tracking by location (calls and forms) so you know where demand is.","Simple reporting that multi-site leadership can actually use."]'::jsonb,
  '[{"value":"+52%","label":"Local Enquiries","description":"Across priority locations in 9 months"},{"value":"Clear","label":"Performance View","description":"Clear view of which branches need support and where demand is strongest"},{"value":"Better","label":"Brand Consistency","description":"Brand consistency improved while local relevance went up"}]'::jsonb,
  'Before, each location did its own thing. Now we have a system – Google knows where to send people, and so do we.',
  'Rachel Foster',
  'Head of Marketing',
  'National Fitness Co.',
  '[{"question":"We already have a centralised CMS – can you work with it?","answer":"Yes. We design location templates that scale inside your current stack, then handle the rollout."},{"question":"How do you avoid duplicate content across locations?","answer":"By planning unique elements per location (services, proof, FAQs, team) and using smart templates instead of copy-paste pages."},{"question":"Can you train our local teams to maintain profiles?","answer":"Yes. We can provide playbooks and light training so branches don''t accidentally undo the work."},{"question":"Will this interfere with our paid campaigns?","answer":"No. Local SEO complements paid by capturing organic demand and building brand trust – and we coordinate with paid teams on targeting."}]'::jsonb,
  NULL,
  NULL,
  NULL,
  'multi-location seo',
  'SEO for Multi-Location Brands | Avorria',
  'SEO for franchise and multi-location brands. Location page strategy, Google Business Profile optimization and consolidated performance reporting.',
  '["multi-location-web-design","franchise-local-seo"]'::jsonb,
  '["multi-location-strategy","local-seo-scaling"]'::jsonb,
  true,
  true
),
-- Web Design for Automotive Aftermarket
(
  'web-design-automotive-aftermarket',
  'Web Design for Automotive Aftermarket',
  'service-industry',
  'web-design',
  'automotive-aftermarket',
  NULL,
  'Web design for automotive aftermarket that turns car enthusiasts into customers.',
  'Performance upgrades, custom builds, detailing – we build websites that showcase your work and generate leads from drivers who are ready to spend.',
  'Discuss your automotive website',
  'Get an automotive website audit',
  '["Your site looks dated compared to the quality of your work.","Gallery images don''t do your builds justice.","There''s no clear path for enquiries – just a phone number in the corner.","You''re invisible for the local searches your customers actually make.","You can''t tell which marketing efforts are bringing in real work."]'::jsonb,
  '["Showstopping design that matches the quality of your builds.","Dynamic galleries and project showcases with proper filtering.","Conversion-focused layout with clear service pages and booking flows.","Local SEO setup so you rank for relevant searches in your area.","Call and form tracking so you know what''s working."]'::jsonb,
  '[{"value":"+156%","label":"Enquiries","description":"Increase in qualified enquiries after new site launch"},{"value":"3x","label":"Gallery Views","description":"More time spent viewing project galleries"},{"value":"+84%","label":"Local Visibility","description":"Improvement in local search rankings for key terms"}]'::jsonb,
  'Our old site didn''t reflect what we do. The new one shows off our work properly and the phone rings more – from people who know what they want.',
  'Dan Patterson',
  'Owner',
  'DP Auto Repair & Performance',
  '[{"question":"We''re a small shop – is a premium website overkill?","answer":"Your website is often the first impression. A premium site that matches your work quality pays for itself in better leads and higher-ticket jobs."},{"question":"Can you handle our service bookings online?","answer":"Yes. We can integrate booking systems, request forms and even deposit payments."},{"question":"How do you showcase our builds effectively?","answer":"High-quality galleries with filtering, before/after sliders, and project detail pages that tell the story of each build."},{"question":"What about parts sales or e-commerce?","answer":"We can build catalogues and e-commerce for parts where it makes sense, but focus first on what drives your core revenue."}]'::jsonb,
  '[{"title":"Discovery & Positioning","description":"Understand your specialty, target customers and competitive landscape."},{"title":"Design & Content","description":"Create a site that showcases your work with stunning visuals and clear CTAs."},{"title":"Build & Optimise","description":"Development with SEO baked in and conversion tracking from day one."},{"title":"Launch & Grow","description":"Ongoing support to keep the site fresh with new projects and optimise for performance."}]'::jsonb,
  'We work with performance shops, detailers, custom builders and specialist repair shops. We understand car culture and what makes enthusiasts tick – because we''re enthusiasts too.',
  'Automotive website projects typically start from £5,000 for a core site up to £15,000+ for full e-commerce and booking integration.',
  'automotive aftermarket web design',
  'Web Design for Automotive Aftermarket | Avorria',
  'Specialist website design for performance shops, custom builders and automotive specialists. Showcase your work and generate quality leads.',
  '["dp-auto-performance","automotive-garage-website"]'::jsonb,
  '["automotive-marketing-guide","garage-website-tips"]'::jsonb,
  true,
  true
),
-- Web Design for Facilities Management
(
  'web-design-facilities-management',
  'Web Design for Facilities Management',
  'service-industry',
  'web-design',
  'facilities-management',
  NULL,
  'Web design for FM companies that actually generates contracts – not just looks professional.',
  'We build FM websites that position you for the work you want: sector-specific landing pages, clear service architecture, and AI-driven enquiry workflows.',
  'Discuss your FM website project',
  'See EntireFM case study (+156% enquiries)',
  '["Your site looks generic – like every other FM company.","Services are buried or unclear to different buyer personas.","No tracking on which pages or channels generate actual opportunities.","Property managers can''t quickly find if you serve their sector.","The site was built 5+ years ago and hasn''t evolved with your business."]'::jsonb,
  '["Sector-specific landing pages (commercial, industrial, healthcare, retail).","Clear service architecture separating hard/soft services.","AI-powered enquiry qualification and chatbot integration.","Mobile-first design that works for on-site managers.","Analytics tracking from first visit through to contract."]'::jsonb,
  '[{"value":"+156%","label":"Enquiries","description":"Increase for EntireFM after full website rebuild"},{"value":"40%","label":"Better Lead Quality","description":"Higher quality leads through AI pre-qualification"},{"value":"3x","label":"Sector Coverage","description":"More effective targeting across commercial, industrial, healthcare"}]'::jsonb,
  'Our old site listed services but didn''t speak to different sectors. The new site positions us exactly right for commercial and industrial clients – enquiries have tripled.',
  'Richard Hartley',
  'Managing Director',
  'EntireFM',
  '[{"question":"Do you understand FM sector complexity?","answer":"Yes. We know the difference between hard and soft services, PPM scheduling, CAFM systems and compliance. We built the EntireFM site that drove 156% more enquiries."},{"question":"Can you integrate with our CAFM/helpdesk?","answer":"Absolutely. We''ve integrated with major CAFM platforms and can showcase live KPIs and job tracking on your site."},{"question":"How do you handle multi-sector targeting?","answer":"Dedicated sector pages for each market you serve – commercial, industrial, healthcare, retail – each speaking the language of that sector."},{"question":"What about compliance and certifications?","answer":"We prominently feature ISO, SafeContractor, CHAS and other certifications throughout the buyer journey."}]'::jsonb,
  '[{"title":"Discovery & Sector Mapping","description":"Map your service sectors, buyer personas and competitive positioning."},{"title":"Architecture & Design","description":"Build information architecture and design that speaks to each sector."},{"title":"Content & Integration","description":"Premium website with CAFM showcases, helpdesk demos, AI-driven enquiry workflows."},{"title":"Launch & Optimise","description":"Ongoing SEO, CRO sprints, and performance monitoring to improve enquiry quality."}]'::jsonb,
  'We understand the FM sector inside and out. We know the difference between hard and soft services, understand PPM scheduling, CAFM systems, and compliance requirements.',
  'FM website projects typically range from £8,000–£25,000 depending on scope, integrations, and sector coverage requirements.',
  'facilities management website design',
  'Web Design for Facilities Management Companies | Avorria',
  'Specialist website design for facilities management companies. See how we helped EntireFM increase enquiries by 156%. CAFM integration, AI workflows, sector-specific architecture.',
  '["entirefm-rebrand","commercial-fm-website"]'::jsonb,
  '["fm-digital-transformation","cafm-integration-guide"]'::jsonb,
  true,
  true
);